// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqprvrrncpqhpfxafeuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcHJ2cnJuY3BxaHBmeGFmZXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODExNjcsImV4cCI6MjA2Mzk1NzE2N30.k589z5xDaS10D4CZaNq16Egixr8CBk5C0InRt1BTdTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);